server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true # Needed to be true so other client instances could be registered


logging:
  level:
    com:
      netflix:
        eureka: INFO
        discovery: INFO

